config:
  ul-style:
    style: 'dash'
  ul-indent:
    indent: 2
  line-length:
    line_length: 120 # Line length 80 is far to short
  no-trailing-punctuation:
    punctuation: '.,;:!。，；:' # List of not allowed
  ol-prefix:
    style: 'one_or_ordered' # Ordered list item prefix
  no-inline-html: false # Allow inline HTML
  no-emphasis-as-heading: false # Emphasis used instead of a heading

# Define glob expressions to use (only valid at root)
globs:
  - '**/*.md'

# Ignore files referenced by .gitignore (only valid at root)
gitignore: true

# Define glob expressions to ignore
ignores:
  - 'node_modules/**/*.md'
  - 'vendor/**/*.md'

# Disable progress on stdout (only valid at root)
noProgress: false

outputFormatters:
  - - markdownlint-cli2-formatter-codequality
    - name: logs/markdownlint.json
    - markdownlint-cli2-formatter-junit
    - name: logs/markdownlint-junit.xml
